/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.pidecita;

import java.util.Calendar;
import java.util.GregorianCalendar;

import org.pidecita.calendario.Calendario;
import org.pidecita.calendario.Cita;
import org.pidecita.cliente.Cliente;
import org.pidecita.servicios.LimpiezaFacial;
import org.pidecita.servicios.MicroPigmentacion;
import org.pidecita.servicios.Servicio;

public class App {
    public static void main(String[] args) {
        Cliente manola = new Cliente("Manola", 608080808);
        Cliente manoli = new Cliente("Manoli", 608080808);
        Servicio limpFacial = new LimpiezaFacial();
        Servicio micro = new MicroPigmentacion();
        
        Calendar fecha = new GregorianCalendar(2024, Calendar.JUNE, 1, 10, 30);

        Cita cita = new Cita(limpFacial, manola, fecha);
        Cita citaMicro = new Cita(micro, manoli, fecha);

        Calendario calendario = new Calendario();

        calendario.addCita(cita);
        calendario.addCita(citaMicro);

        

    }
}
